// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcuqlcycerdkzyavxskw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jdXFsY3ljZXJka3p5YXZ4c2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDE0NDIsImV4cCI6MjA3MTc3NzQ0Mn0.0pGNZ9we3S2umSXoyYJmwGh_3lE61M5ZhmhTrNw5U2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});